BookStoreWebApp/Areas/Admin/Controllers/BookAdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BookStoreWebApp;
using BookStoreWebApp.Areas.Admin.Models;
using System.IO;
using System.Data.Entity.Validation;
using System.Diagnostics;
using BookStoreWebApp.Controllers;

namespace BookStoreWebApp.Areas.Admin.Controllers
{
    public class BookAdminController : AdminController
    {
        private BookStoreMDFEntities db = new BookStoreMDFEntities();

        // GET: Admin/BookAdmin
        public ActionResult Index()
        {
            var books = db.Books.Include(b => b.Author).Include(b => b.Category);
            return View(books.ToList());
        }

        // GET: Admin/BookAdmin/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/BookAdmin/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BookDTO model)
        {
            const string folderpath = "/Content/images/";
            if (ModelState.IsValid)
            {

                if (model.Photo != null && model.PhotoHover != null && model.Photo.ContentLength > 0 && model.PhotoHover.ContentLength > 0)
                {
                    var photopath = Path.Combine(Server.MapPath(folderpath), model.Photo.FileName);
                    var photopathhover = Path.Combine(Server.MapPath(folderpath), model.PhotoHover.FileName);
                    model.Photo.SaveAs(photopath);
                    model.PhotoHover.SaveAs(photopathhover);
                }
                Author author=new Author();
                Category category = new Category();
                Book book = new Book();
                book.Title = model.Title;
                book.Price = model.Price;
                book.Description = model.Description;
                book.DateOfPublish = model.DateOfPublish;
                book.Stock = model.Stock ?? 1;
                book.Rating = model.Rating ?? 1;
                if(!db.Authors.Any(x=>x.FirstName==model.AuthorFirstName&&x.LastName==model.AuthorLastName))
                {
                    author.FirstName = model.AuthorFirstName;
                    author.LastName = model.AuthorLastName; 
                    db.Authors.Add(author);
                    db.SaveChanges();
                }
                else
                {
                    author = db.Authors.First(x=>x.FirstName==model.AuthorFirstName);
                }
                if (!db.Categories.Any(x=>x.CategoryName==model.Category))
                {
                    category.CategoryName = model.Category;
                    db.Categories.Add(category);
                    db.SaveChanges();
                }
                else
                {
                    category = db.Categories.First(x => x.CategoryName == model.Category);
                }
                book.CategoryID = category.ID;
                book.AuthorID = author.ID;
                book.PhotoUrl = folderpath + model.Photo.FileName;
                book.PhotoUrlHover = folderpath + model.PhotoHover.FileName;
                try {
                    db.Books.Add(book);
                    db.SaveChanges();
                }
                catch (DbEntityValidationException dbEx)
                {
                    foreach (var validationErrors in dbEx.EntityValidationErrors)
                    {
                        foreach (var validationError in validationErrors.ValidationErrors)
                        {
                            Trace.TraceInformation("Property: {0} Error: {1}",
                                                    validationError.PropertyName,
                                                    validationError.ErrorMessage);
                        }
                    }
                }
                return RedirectToAction("Index");
            }
            return View();
        }

        // GET: Admin/BookAdmin/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            BookDTO dto = new BookDTO();
            dto.ID = book.ID;
            dto.Title = book.Title;
            dto.Price = book.Price;
            dto.Description = book.Description;
            dto.Category = book.Category.CategoryName;
            dto.AuthorFirstName = book.Author.FirstName;
            dto.AuthorLastName = book.Author.LastName;
            dto.DateOfPublish = book.DateOfPublish;
            dto.Stock = book.Stock;
            dto.Rating = book.Rating;
            return View(dto);
        }

        // POST: Admin/BookAdmin/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(BookDTO model)
        {
            const string folderpath = "~/Content/images/";
            if (ModelState.IsValid)
            {
                Author author = new Author();
                Category category = new Category();
                Book book = new Book();
                if (model.Photo != null && model.PhotoHover != null && model.Photo.ContentLength > 0 && model.PhotoHover.ContentLength > 0)
                {
                    var photopath = Path.Combine(Server.MapPath(folderpath), model.Photo.FileName);
                    var photopathhover = Path.Combine(Server.MapPath(folderpath), model.PhotoHover.FileName);
                    model.Photo.SaveAs(photopath);
                    model.PhotoHover.SaveAs(photopathhover);
                }
                book.ID = model.ID;
                book.Title = model.Title;
                book.Price = model.Price;
                book.Description = model.Description;
                book.DateOfPublish = model.DateOfPublish;
                book.Stock = model.Stock;
                book.Rating = model.Rating;
                if (!db.Authors.Any(x => x.FirstName == model.AuthorFirstName && x.LastName == model.AuthorLastName))
                {
                    author.FirstName = model.AuthorFirstName;
                    author.LastName = model.AuthorLastName;
                    db.Authors.Add(author);
                    db.SaveChanges();
                }
                else
                {
                    author = db.Authors.First(x => x.FirstName == model.AuthorFirstName);
                }
                if (!db.Categories.Any(x => x.CategoryName == model.Category))
                {
                    category.CategoryName = model.Category;
                    db.Categories.Add(category);
                    db.SaveChanges();
                }
                else
                {
                    category = db.Categories.First(x => x.CategoryName == model.Category);
                }
                book.CategoryID = category.ID;
                book.AuthorID = author.ID;
                if (model.Photo != null && model.Photo.ContentLength > 0) { 
                book.PhotoUrl = folderpath + model.Photo.FileName;
                }
                if (model.PhotoHover != null && model.PhotoHover.ContentLength > 0) { 
                book.PhotoUrlHover = folderpath + model.PhotoHover.FileName;
                }
                db.Entry(book).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        // GET: Admin/BookAdmin/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // POST: Admin/BookAdmin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Book book = db.Books.Find(id);
            db.Books.Remove(book);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BookStoreWebApp/Areas/Admin/Controllers/RoleController.cs
using BookStoreWebApp.Areas.Admin.Models;
using BookStoreWebApp.Controllers;
using BookStoreWebApp.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookStoreWebApp.Areas.Admin.Controllers
{
    public class RoleController : AdminController
    {
        ApplicationDbContext context = new ApplicationDbContext();
        // GET: Admin/Role
        public ActionResult Index()
        {
           
            var roleStore = new RoleStore<IdentityRole>(context);
            var roleManager = new RoleManager<IdentityRole>(roleStore);

            var model = roleManager.Roles.ToList();
            return View(model);
        }
        public ActionResult AddRole()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddRole(RoleModel role)
        {
            var roleStore = new RoleStore<IdentityRole>(context);
            var roleManager = new RoleManager<IdentityRole>(roleStore);
            
           if (roleManager.RoleExists(role.RoleName) == false)
          {
           roleManager.Create(new IdentityRole(role.RoleName));
          }
            
             return RedirectToAction("Index");
        }

        public ActionResult RoleUser()
        {
            return View();
        }


        [HttpPost]
        public ActionResult RoleUser(AddRoleUser roleUser)
        {
            var roleStore = new RoleStore<IdentityRole>(context);
            var roleManager = new RoleManager<IdentityRole>(roleStore);

            var userStore = new UserStore<ApplicationUser>(context);
            var userManager = new UserManager<ApplicationUser>(userStore);


            var kullanici = userManager.FindByName(roleUser.UserName);

            if (!userManager.IsInRole(kullanici.Id, roleUser.RoleName))
            {
                userManager.AddToRole(kullanici.Id, roleUser.RoleName);
            }

            return RedirectToAction("Index");
        }
}
}

BookStoreWebApp/Areas/Admin/Views/Role/AddRole.cshtml
@model BookStoreWebApp.Areas.Admin.Models.RoleModel

@{
    ViewBag.Title = "AddRole";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Add Role</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <br />
                @using (Html.BeginForm())
                {
                    @Html.TextBoxFor(Model => Model.RoleName)
                    <input type="submit" class="btn btn-success" />
                }

            </div>
        </div>
    </div>
</div>

BookStoreWebApp/Areas/Admin/Views/Role/Index.cshtml
@model List<Microsoft.AspNet.Identity.EntityFramework.IdentityRole>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}



<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>@Resources.Home.roles</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <ul>
                    @foreach (var item in Model)
                    {
                        <li><h1 class="title">@item.Name: <span>@item.Users.Count</span></h1></li>
                    }
                </ul>
                @Html.ActionLink("AddRole", "AddRole", null, new { @class= "btn btn-round btn-success" })

            </div>
        </div>
    </div>

</div>

@*<div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_content">
                    <table class="table table-striped projects">
                        <thead>
                            <tr>
                                <th style="width: 1%">#</th>
                                <th style="width: 15%">@Html.DisplayNameFor(model => model.Title)</th>
                                <th>@Html.DisplayNameFor(model => model.Category.CategoryName)</th>
                                <th>@Html.DisplayNameFor(model => model.Author.FirstName)</th>
                                <th>@Html.DisplayNameFor(model => model.Price)</th>
                                <th>@Html.DisplayNameFor(model => model.Description)</th>
                                <th>@Html.DisplayNameFor(model => model.DateOfPublish)</th>
                                <th>Stock</th>
                                <th style="width: 20%">#Edit</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>#</td>
                                    <td>
                                        @Truncate(item.Title, 15)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Category.CategoryName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Author.FirstName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Price)
                                    </td>
                                    <td>
                                        @Truncate(item.Description, 15)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.DateOfPublish)
                                    </td>
                                    <td class="project_progress">
                                        <div class="progress progress_sm">
                                            <div class="progress-bar bg-green" role="progressbar" data-transitiongoal="@item.Stock"></div>
                                        </div>
                                        <small>@item.Stock items left</small>
                                    </td>
                                    <td>
                                        <a href="@Url.Action("Edit","BookAdmin", new { id=item.ID})" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit </a>
                                        <a href="@Url.Action("Delete","BookAdmin", new { id=item.ID})" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> Delete </a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>*@

BookStoreWebApp/Areas/Admin/Views/Role/RoleUser.cshtml
@model BookStoreWebApp.Areas.Admin.Models.AddRoleUser
@{
    ViewBag.Title = "RoleUser";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Add Role</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <br />
                @using (Html.BeginForm("AddUser", "Role"))
                {
                    @Html.LabelFor(m => m.UserName) <br/> @Html.TextBoxFor(m => m.UserName)
                    <br />
                    @Html.LabelFor(m => m.RoleName)  <br/>@Html.TextBoxFor(m => m.RoleName)
                    <br />
                    <br/>
                    <input type="submit" class="btn btn-success" />
                }
            </div>
        </div>
    </div>
</div>