BookStoreWebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookStoreWebApp.Models;

namespace BookStoreWebApp.Controllers
{

    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }


    }
}

BookStoreWebApp/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using PagedList;
using System.Net;

namespace BookStoreWebApp.Controllers
{
   
    public class ShopController : Controller
    {
        private BookStoreMDFEntities db = new BookStoreMDFEntities();
        // GET: Shop
        public ActionResult Index(string sortOrder,string currentFilter,  string searchString,int? page)
        {

            ViewBag.CurrentSort = sortOrder;

            if (searchString!=null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";

            var books = db.Books.Include("Category").ToList();

            if(!String.IsNullOrEmpty(searchString))
            {
                books = books.Where(x => x.Title.ToUpper().Contains(searchString.ToUpper()) || x.Category.CategoryName.ToUpper().Contains(searchString.ToUpper())).ToList();
            }
            switch (sortOrder)
            {
                case "name_desc":
                    books = books.OrderByDescending(x => x.Title).ToList();
                    break;
                case "Date":
                    books = books.OrderBy(x => x.DateOfPublish).ToList();
                    break;
                case "date_desc":
                    books = books.OrderByDescending(x => x.DateOfPublish).ToList();
                    break;
                default:
                    books = books.OrderBy(x => x.Title).ToList();
                    break;
            }
           
            int pageNumber = (page ?? 1);
            return View(books.ToPagedList(pageNumber, 6));
        }
        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book= db.Books.Find(id);
            if (book== null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        [ChildActionOnly]
        public ActionResult Related(string category)
        {
            var books = db.Books.Select(x => x);
            if (!String.IsNullOrEmpty(category))
            {
                books = books.Where(x => x.Category.CategoryName == category).Take(3);
            }
            else
            {
                books = books.Take(3);
            }
            return View(books);
        }
        [Authorize(Roles ="user")]
        public ActionResult CartAction()
        {
            return View();
        }
    }
}

BookStoreWebApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<div id="page-header">
    <h1>
        @Resources.Home.about
        <span class="small-bottom-border big"></span><!-- small-bottom-border -->
    </h1>
    <div class="md-margin"></div><!-- space -->
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <p class="page-header-desc"><p>
            </div><!-- End .col-md-8 -->
        </div><!-- End .row -->
    </div> <!-- End .container -->
</div><!-- End #page-header -->

<div class="md-margin2x"></div><!-- space -->

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <header class="content-title">
                        <h2 class="title">@Resources.Home.Whoweare</h2>
                        <div class="xss-margin"></div><!-- space -->
                    </header>
                   <p>@Resources.Home.whotext</p>
                    <div class="visible-xs md-margin"></div>
                </div><!-- End .col-md-6 -->

                <div class="col-md-6 col-sm-6 col-xs-12">
                    <header class="content-title">
                        <h2 class="title">@Resources.Home.skill</h2>
                        <div class="xss-margin"></div><!-- space -->
                    </header>

                    <div class="progress-container">
                        <h4>Asp.net MVC</h4>
                        <div class="progress">
                            <div class="progress-bar progress-bar-custom progress-animate" role="progressbar" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100" data-width="85">
                                <span class="progress-text">85%</span>
                            </div><!-- End .progress-bar -->
                        </div><!-- End .progress -->
                    </div><!-- End .progress-container -->

                    <div class="progress-container">
                        <h4>photoshop</h4>
                        <div class="progress">
                            <div class="progress-bar progress-bar-custom progress-animate" role="progressbar" aria-valuenow="73" aria-valuemin="0" aria-valuemax="100" data-width="73">
                                <span class="progress-text">73%</span>
                            </div><!-- End .progress-bar -->
                        </div><!-- End .progress -->
                    </div><!-- End .progress-container -->

                    <div class="progress-container">
                        <h4>Html/css</h4>
                        <div class="progress">
                            <div class="progress-bar progress-bar-custom progress-animate" role="progressbar" aria-valuenow="92" aria-valuemin="0" aria-valuemax="100" data-width="92">
                                <span class="progress-text">92%</span>
                            </div><!-- End .progress-bar -->
                        </div><!-- End .progress -->
                    </div><!-- End .progress-container -->

                    <div class="progress-container">
                        <h4>Illustrator</h4>
                        <div class="progress">
                            <div class="progress-bar progress-bar-custom progress-animate" role="progressbar" aria-valuenow="69" aria-valuemin="0" aria-valuemax="100" data-width="69">
                                <span class="progress-text">69%</span>
                            </div><!-- End .progress-bar -->
                        </div><!-- End .progress -->
                    </div><!-- End .progress-container -->

                    <div class="progress-container">
                        <h4>Programming</h4>
                        <div class="progress">
                            <div class="progress-bar progress-bar-custom progress-animate" role="progressbar" aria-valuenow="87" aria-valuemin="0" aria-valuemax="100" data-width="87">
                                <span class="progress-text">87%</span>
                            </div><!-- End .progress-bar -->
                        </div><!-- End .progress -->
                    </div><!-- End .progress-container -->

                </div><!-- End .col-md-6 -->
            </div><!-- End.row -->

            <div class="xlg-margin2x"></div><!-- space -->
        </div><!-- End .col-md-12 -->
    </div><!-- End.row -->
</div><!-- End .container -->
<div class="xs-margin"></div>

BookStoreWebApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<div id="breadcrumb-container">
    <div class="container">
        <ul class="breadcrumb">
            <li><a href="index.html">@Resources.Home.home</a></li>
            <li class="active">@Resources.Home.contact</li>
        </ul>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <header class="content-title">
                <h1 class="title">@Resources.Home.contact</h1>
                <p class="title-desc">@Resources.Home.hearfromyou</p>
            </header>
            <div class="xs-margin"></div><!-- space -->
            <div class="row">

                <div class="col-md-12">
                    <div id="map">
                        <!-- Google - Map - Api -->
                    </div><!-- End #map -->
                </div><!-- End .col-md-12 -->

                <div class="col-md-8 col-sm-8 col-xs-12">
                    <h2 class="sub-title">@Resources.Home.comment</h2>
                    <div class="row">
                        <form action="#" id="contact-form">
                            <div class="col-md-6 col-sm-12 col-xs-12">
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="input-icon input-icon-user"></span><span class="input-text">@Resources.Home.name&#42;</span></span>
                                    <input type="text" name="contact-name" id="contact-name" required class="form-control input-lg" placeholder="Your Name">
                                </div><!-- End .input-group -->
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="input-icon input-icon-email"></span><span class="input-text">@Resources.Home.email&#42;</span></span>
                                    <input type="email" name="contact-email" id="contact-email" required class="form-control input-lg" placeholder="Your Email">
                                </div><!-- End .input-group -->
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="input-icon input-icon-subject"></span><span class="input-text">@Resources.Home.Subject&#42;</span></span>
                                    <input type="text" name="contact-subject" id="contact-subject" required class="form-control input-lg" placeholder="Subject">
                                </div><!-- End .input-group -->
                     
                            </div><!-- End .col-md-6 -->

                            <div class="col-md-6 col-sm-12 col-xs-12">
                                <div class="input-group textarea-container">
                                    <span class="input-group-addon"><span class="input-icon input-icon-message"></span><span class="input-text">Your Comment</span></span>
                                    <textarea name="contact-message" id="contact-message" class="form-control" cols="30" rows="6" placeholder="Your Message"></textarea>
                                </div><!-- End .input-group -->
                                <input type="submit" value="SUBMIT" class="btn btn-custom-2 md-margin">
                            </div><!-- End .col-md-6 -->
                        </form>
                    </div><!-- End .row -->

                </div><!-- End .col-md-8 -->
            </div><!-- End .row -->

        </div><!-- End .col-md-12 -->
    </div><!-- End .row -->
</div><!-- End .container -->

@section maps{<<script type="text/javascript">

    var map;
    function initMap() {
      map = new google.maps.Map(document.getElementById('map'), {
          center: { lat: 40.746234, lng: 30.349445 },
        zoom: 16
      });
    }
    </script>
    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB9QvNTJbud3lVTmzdTzHtj875IPNh_Ltw&callback=initMap">
    </script>}

BookStoreWebApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="container">
    <div class="row">
        <div class="col-md-12">

            <div class="row slider-position">
                <div class="md-margin"></div><!-- space -->

                <div class="col-md-3 col-sm-4 col-xs-12 sidebar">

                    @{ Html.RenderAction("Related", "Shop");}

                    @*@{ Html.RenderAction("Related","Shop");}*@

                </div><!-- End .col-md-3 -->

                <div class="col-md-9 col-sm-8 col-xs-12 main-content ">
                    <div id="slider-rev-container">
                        <div id="slider-rev">
                            <ul>
                                <li data-transition="random" data-saveperformance="on" data-title="Easy to Customize">
                                    <img src="~/Content/images/revslider/dummy.png" alt="slidebg1" data-lazyload="/Content/images/homeslider/slide1.jpg" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat">
                                    <div class="tp-caption rev-title lft ltt" data-x="530" data-y="140" data-speed="1100" data-start="300" data-endspeed="350">
                                        Enjoy Wide  Book <br>Posibilities
                                    </div>
                                    <div class="tp-caption lfr ltr" data-x="530" data-y="250" data-speed="1500" data-start="450" data-endspeed="100" data-easing="Power3.easeIn">
                                        <img src="~/Content/images/homeslider/bullet.png" alt="bullet">
                                    </div>
                                    <div class="tp-caption rev-list lfr ltr" data-x="575" data-y="246" data-speed="1500" data-start="550"
                                         data-easing="Power3.easeIn" data-endspeed="150">
                                       Cheapest Books
                                    </div>

                                    <div class="tp-caption lfr ltr" data-x="530" data-y="290" data-speed="1500" data-start="650" data-endspeed="180" data-easing="Power3.easeIn">
                                        <img src="~/Content/images/homeslider/bullet.png" alt="bullet">
                                    </div>

                                    <div class="tp-caption rev-list lfr ltr" data-x="575" data-y="286" data-speed="1500" data-start="800"
                                         data-easing="Power3.easeIn" data-endspeed="230">
                                        Best in the market
                                    </div>

                                    <div class="tp-caption lfr ltr" data-x="530" data-y="330" data-speed="1500" data-start="950" data-endspeed="260" data-easing="Power3.easeIn">
                                        <img src="~/Content/images/homeslider/bullet.png" alt="bullet">
                                    </div>

                                    <div class="tp-caption rev-list lfr ltr" data-x="575" data-y="326" data-speed="1500" data-start="1100"
                                         data-easing="Power3.easeIn" data-endspeed="290">
                                        Variaty of subjects
                                    </div>
                                </li>

                                <li data-transition="random" data-saveperformance="on" data-title="Powerful Template">

                                    <img src="~/Content/images/revslider/dummy.png" alt="slidebg3" data-lazyload="/Content/images/homeslider/slide3.jpg" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat">
                                    <div class="tp-caption rev-title lfl ltl" data-x="40" data-y="140" data-speed="800" data-start="300" data-endspeed="350">
                                        BookStore <br>Every thing you need
                                    </div>

                                    <div class="tp-caption sfr stl" data-x="40" data-y="240" data-speed="1000" data-start="500" data-endspeed="100">
                                        <img src="~/Content/images/homeslider/bullet-reverse.png" alt="bullet">
                                    </div>

                                    <div class="tp-caption rev-list sfr stl" data-x="85" data-y="236" data-speed="1000" data-start="650"
                                         data-endspeed="150">
                                        Science
                                    </div>

                                    <div class="tp-caption sfr stl" data-x="40" data-y="282" data-speed="1000" data-start="750" data-endspeed="180">
                                        <img src="~/Content/images/homeslider/bullet-reverse.png" alt="bullet">
                                    </div>

                                    <div class="tp-caption rev-list sfr stl" data-x="85" data-y="278" data-speed="1000" data-start="900"
                                         data-endspeed="230">
                                        Physics
                                    </div>

                                    <div class="tp-caption sfr stl" data-x="40" data-y="324" data-speed="1000" data-start="1000" data-endspeed="260">
                                        <img src="~/Content/images/homeslider/bullet-reverse.png" alt="bullet">
                                    </div>

                                    <div class="tp-caption rev-list sfr stl" data-x="85" data-y="320" data-speed="1000" data-start="1150"
                                         data-endspeed="290">
                                        Computer
                                    </div>

                                    <div class="tp-caption sfr stl" data-x="40" data-y="366" data-speed="1000" data-start="1250" data-endspeed="320">
                                        <img src="~/Content/images/homeslider/bullet-reverse.png" alt="bullet">
                                    </div>

                                    <div class="tp-caption rev-list sfr stl" data-x="85" data-y="362" data-speed="1000" data-start="1400"
                                         data-endspeed="350">
                                        &amp;Other
                                    </div>
                                </li>

                            </ul>
                        </div><!-- End #slider-rev -->
                    </div><!-- End #slider-rev-container -->

                    <div class="lg-margin"></div><!-- Space -->
                    <div class="lg-margin"></div><!-- Space -->
                    <div class="lg-margin"></div><!-- Space -->

                    <div class="row">
                        <div class="col-md-6 col-sm-12 col-xs-12">
                            <header class="content-title">
                                <h2 class="title">@Resources.Home.Whoweare</h2>
                            </header>
                            <div class="xs-margin"></div><!-- Space -->
                            <p>@Resources.Home.whotext</p>
                        </div><!-- End .col-md-6 -->
                        <div class="col-md-6 col-sm-12 col-xs-12">
                            <div class="sm-margin visible-xs"></div><!-- space -->
                            <img src="~/Content/images/team1.jpg" alt="Our Team" class="img-responsive">
                        </div><!-- End .col-md-6 -->
                    </div><!-- End .row -->
                    <div class="xlg-margin"></div><!-- Space -->

                    <div class="md-margin2x"></div><!-- Space -->
                </div><!-- End .col-md-9 -->

            </div><!-- End .row -->

        </div><!-- End .col-md-12 -->
    </div><!-- End .row -->
</div><!-- End .container -->